CREATE OR REPLACE FUNCTION distribution.check_true(condition boolean,label text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF condition IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: %',label; END IF; RAISE NOTICE 'PASS: %',label; END $$;
CREATE OR REPLACE FUNCTION distribution.expect_error(action text,p jsonb,role text,pattern text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN BEGIN PERFORM distribution.apply_action(action,p,null,role,'qa',gen_random_uuid()); EXCEPTION WHEN OTHERS THEN IF SQLERRM NOT ILIKE '%'||pattern||'%' THEN RAISE EXCEPTION 'Wrong error: % (expected %)',SQLERRM,pattern; END IF; RAISE NOTICE 'PASS: rejects %',pattern; RETURN; END; RAISE EXCEPTION 'Expected rejection: %',pattern; END $$;
DO $$
DECLARE p uuid; p2 uuid; c uuid; v uuid; u uuid; sale uuid; request_uuid uuid; result jsonb; payload jsonb;
BEGIN
 INSERT INTO distribution.users(name,email,role) VALUES('Isolated test representative','isolated@example.invalid','salesman') RETURNING users.id INTO u;
 PERFORM distribution.check_true((distribution.resolve_member('owner@example.invalid','Isolated owner')->>'role')='owner','Owner bootstrap works when staff already exist');
 PERFORM distribution.check_true(distribution.resolve_member('unknown@example.invalid','Unknown') IS NULL,'Unknown accounts are denied after owner setup');
 UPDATE distribution.users SET active=false WHERE users.id=u;
 PERFORM distribution.check_true(distribution.resolve_member('isolated@example.invalid','Inactive') IS NULL,'Inactive accounts are denied');
 UPDATE distribution.users SET active=true WHERE users.id=u;
 result:=distribution.apply_action('product','{"name":"Isolated test product","sku":"QA-ONLY","brand":"","category":"","unit":"Packet","box_size":12,"carton_size":144,"price":100,"cost":60,"tax_rate":5,"min_stock":10}',null,'owner','qa',gen_random_uuid()); p:=(result->>'id')::uuid;
 result:=distribution.apply_action('product','{"name":"Isolated second product","sku":"QA-ONLY-2","brand":"","category":"","unit":"Packet","box_size":12,"carton_size":144,"price":50,"cost":30,"tax_rate":0,"min_stock":0}',null,'owner','qa',gen_random_uuid()); p2:=(result->>'id')::uuid;
 INSERT INTO distribution.customers(name,credit_limit) VALUES('Isolated shop',2000) RETURNING id INTO c;
 result:=distribution.apply_action('vehicle',jsonb_build_object('number','QA-ONLY','type','Van','salesman_id',u),null,'owner','qa',gen_random_uuid()); v:=(result->>'id')::uuid;
 PERFORM distribution.apply_action('inventory',jsonb_build_object('product_id',p,'qty',100,'kind','RECEIPT'),null,'owner','qa',gen_random_uuid());
 PERFORM distribution.apply_action('inventory',jsonb_build_object('product_id',p2,'qty',10,'kind','RECEIPT'),null,'owner','qa',gen_random_uuid());
 PERFORM distribution.expect_error('load',jsonb_build_object('vehicle_id',v,'items',jsonb_build_array(jsonb_build_object('product_id',p,'qty',101))),'owner','Insufficient warehouse stock');
 PERFORM distribution.check_true((SELECT warehouse_qty=100 FROM distribution.products WHERE id=p),'Failed load keeps warehouse balance');
 PERFORM distribution.apply_action('load',jsonb_build_object('vehicle_id',v,'items',jsonb_build_array(jsonb_build_object('product_id',p,'qty',30),jsonb_build_object('product_id',p2,'qty',10))),null,'owner','qa',gen_random_uuid());
 PERFORM distribution.check_true((SELECT warehouse_qty=70 FROM distribution.products WHERE id=p),'Load deducts warehouse stock');
 PERFORM distribution.check_true((SELECT qty=30 FROM distribution.vehicle_stock WHERE vehicle_id=v AND product_id=p),'Load adds vehicle stock');
 PERFORM distribution.expect_error('sale',jsonb_build_object('vehicle_id',v,'customer_id',c,'items',jsonb_build_array(jsonb_build_object('product_id',p,'qty',1)),'method','CREDIT','paid',0),'owner','dispatched');
 PERFORM distribution.apply_action('vehicle_status',jsonb_build_object('vehicle_id',v,'status','ON ROUTE'),null,'owner','qa',gen_random_uuid());
 PERFORM distribution.expect_error('sale',jsonb_build_object('vehicle_id',v,'customer_id',c,'items',jsonb_build_array(jsonb_build_object('product_id',p,'qty',31)),'method','CREDIT','paid',0),'owner','Insufficient vehicle stock');
 PERFORM distribution.expect_error('sale',jsonb_build_object('vehicle_id',v,'customer_id',c,'items',jsonb_build_array(jsonb_build_object('product_id',p,'qty',25)),'method','CREDIT','paid',0),'owner','credit limit');
 request_uuid:=gen_random_uuid();payload:=jsonb_build_object('vehicle_id',v,'customer_id',c,'items',jsonb_build_array(jsonb_build_object('product_id',p,'qty',10)),'method','CASH','paid',500,'discount',100);
 result:=distribution.apply_action('sale',payload,null,'owner','qa',request_uuid);sale:=(result->>'id')::uuid;
 PERFORM distribution.check_true((SELECT total=945 AND subtotal=1000 AND tax=45 AND paid=500 FROM distribution.sales WHERE sales.id=sale),'Discounted tax and final total calculated on server');
 PERFORM distribution.check_true((SELECT balance=445 FROM distribution.customers WHERE customers.id=c),'Credit reflects unpaid amount');
 PERFORM distribution.apply_action('sale',payload,null,'owner','qa',request_uuid);
 PERFORM distribution.check_true((SELECT count(*)=1 FROM distribution.sales WHERE customer_id=c),'Retry does not duplicate sale');
 PERFORM distribution.check_true((SELECT qty=20 FROM distribution.vehicle_stock WHERE vehicle_id=v AND product_id=p),'Retry does not deduct stock twice');
 PERFORM distribution.expect_error('payment',jsonb_build_object('customer_id',c,'amount',446,'method','CASH'),'owner','cannot exceed');
 PERFORM distribution.apply_action('payment',jsonb_build_object('customer_id',c,'amount',200,'method','UPI'),null,'accountant','qa',gen_random_uuid());
 PERFORM distribution.check_true((SELECT balance=245 FROM distribution.customers WHERE customers.id=c),'Collection reduces outstanding');
 PERFORM distribution.check_true((SELECT paid=700 FROM distribution.sales WHERE sales.id=sale),'Collection allocated to unpaid invoice');
 PERFORM distribution.expect_error('product','{}','salesman','Permission denied');
 PERFORM distribution.expect_error('sale',payload,'salesman','not assigned');
 PERFORM distribution.expect_error('inventory',jsonb_build_object('product_id',p,'qty',-5,'kind','RECEIPT'),'owner','positive');
 PERFORM distribution.expect_error('reconcile',jsonb_build_object('vehicle_id',v,'decision','PARTIAL','items','[]'::jsonb),'owner','HOLD or UNLOAD');
 PERFORM distribution.expect_error('reconcile',jsonb_build_object('vehicle_id',v,'decision','UNLOAD','items',jsonb_build_array(jsonb_build_object('product_id',p,'physical',20))),'owner','every remaining product');
 payload:=jsonb_build_object('vehicle_id',v,'decision','HOLD','items',jsonb_build_array(jsonb_build_object('product_id',p,'physical',19),jsonb_build_object('product_id',p2,'physical',10)));
 PERFORM distribution.expect_error('reconcile',payload,'owner','reason for stock discrepancies');
 payload:=jsonb_set(payload,'{items,0,physical}','20');
 PERFORM distribution.apply_action('reconcile',payload,null,'owner','qa',gen_random_uuid());
 PERFORM distribution.check_true((SELECT sum(qty)=30 FROM distribution.vehicle_stock WHERE vehicle_id=v),'HOLD retains all remaining stock');
 PERFORM distribution.expect_error('load',jsonb_build_object('vehicle_id',v,'items',jsonb_build_array(jsonb_build_object('product_id',p,'qty',1))),'owner','not available');
 -- Advance only the isolated test vehicle's day to verify next-day carry.
 UPDATE distribution.vehicles SET active_day=active_day-1 WHERE vehicles.id=v;
 UPDATE distribution.vehicle_days SET day=day-1 WHERE vehicle_id=v;
 UPDATE distribution.reconciliations SET day=day-1 WHERE vehicle_id=v;
 PERFORM distribution.apply_action('start_day',jsonb_build_object('vehicle_id',v),null,'owner','qa',gen_random_uuid());
 PERFORM distribution.check_true((SELECT status='LOADED' FROM distribution.vehicles WHERE vehicles.id=v),'Held stock can start a new day without an additional load');
 PERFORM distribution.apply_action('load',jsonb_build_object('vehicle_id',v,'items',jsonb_build_array(jsonb_build_object('product_id',p,'qty',5))),null,'owner','qa',gen_random_uuid());
 PERFORM distribution.check_true((SELECT sum((x->>'qty')::integer)=30 FROM distribution.vehicle_days d,jsonb_array_elements(d.opening) x WHERE d.vehicle_id=v AND d.day=(now() AT TIME ZONE 'Asia/Kolkata')::date),'HOLD becomes next-day opening stock');
 PERFORM distribution.apply_action('reconcile',jsonb_build_object('vehicle_id',v,'decision','UNLOAD','items',jsonb_build_array(jsonb_build_object('product_id',p,'physical',25),jsonb_build_object('product_id',p2,'physical',10))),null,'owner','qa',gen_random_uuid());
 PERFORM distribution.check_true((SELECT sum(qty)=0 FROM distribution.vehicle_stock WHERE vehicle_id=v),'UNLOAD empties the entire vehicle');
 PERFORM distribution.check_true((SELECT warehouse_qty=90 FROM distribution.products WHERE products.id=p),'Stock conserved across loads, sale, HOLD and UNLOAD');
 PERFORM distribution.check_true((SELECT warehouse_qty=10 FROM distribution.products WHERE products.id=p2),'UNLOAD returns every product');
 PERFORM distribution.expect_error('reconcile',payload,'owner','No open vehicle day');
 PERFORM distribution.check_true((SELECT count(*)=0 FROM distribution.products WHERE warehouse_qty<0),'Warehouse stock never negative');
END $$;
