CREATE OR REPLACE FUNCTION distribution.worker_action(a text,p jsonb,u uuid,request uuid DEFAULT gen_random_uuid()) RETURNS jsonb LANGUAGE sql AS $$ SELECT distribution.apply_action(a,p,u,'worker',u::text,request) $$;
DO $$
#variable_conflict use_variable
DECLARE owner_id uuid; worker_id uuid; other_worker uuid; product_id uuid; category_id uuid; unit_id uuid; vehicle_id uuid; customer_id uuid; route_id uuid; report_id uuid; request_id uuid; payload jsonb; result jsonb; snapshot jsonb; stockrow jsonb; person jsonb; today date:=(now() AT TIME ZONE 'Asia/Kolkata')::date;
BEGIN
 SELECT id INTO owner_id FROM distribution.users WHERE email='owner@example.invalid';
 result:=distribution.apply_action('user','{"name":"Isolated worker","email":"worker@example.invalid","role":"worker","active":true}',owner_id,'owner',owner_id::text,gen_random_uuid()); worker_id:=(result->>'id')::uuid;
 INSERT INTO distribution.users(name,email,role) VALUES('Other isolated worker','other-worker@example.invalid','worker') RETURNING id INTO other_worker;
 PERFORM distribution.check_true((SELECT role='worker' FROM distribution.users WHERE id=worker_id),'Admin can create a worker account');
 PERFORM distribution.auth_expect_error(format('SELECT distribution.worker_action(%L,%L,%L)','user','{}',worker_id),'Permission denied');
 PERFORM distribution.auth_expect_error(format('SELECT distribution.worker_action(%L,%L,%L)','settings','{}',worker_id),'Permission denied');
 result:=distribution.worker_action('item_type','{"kind":"category","name":"Worker category"}',worker_id); category_id:=(result->>'id')::uuid;
 result:=distribution.worker_action('item_type','{"kind":"unit","name":"Worker unit"}',worker_id); unit_id:=(result->>'id')::uuid;
 payload:='{"name":"Worker product","sku":"WORKER-ONLY","brand":"","category":" worker CATEGORY ","unit":"worker UNIT","box_size":12,"carton_size":144,"price":10,"cost":7,"tax_rate":0,"min_stock":5}';
 request_id:=gen_random_uuid();result:=distribution.worker_action('product',payload,worker_id,request_id);product_id:=(result->>'id')::uuid;
 PERFORM distribution.worker_action('product',payload,worker_id,request_id);
 PERFORM distribution.check_true((SELECT count(*)=1 FROM distribution.products WHERE sku='WORKER-ONLY'),'Canonical item types preserve retry idempotency');
 PERFORM distribution.check_true((SELECT category='Worker category' AND unit='Worker unit' FROM distribution.products WHERE id=product_id),'Products reuse canonical categories and packaging units');
 PERFORM distribution.check_true((SELECT count(*)=1 FROM distribution.item_types WHERE kind='category' AND lower(name)='worker category'),'Item types do not duplicate across letter case');
 PERFORM distribution.worker_action('item_type',jsonb_build_object('id',category_id,'kind','category','name','Renamed worker category'),worker_id);
 PERFORM distribution.check_true((SELECT category='Renamed worker category' FROM distribution.products WHERE id=product_id),'Renaming a category updates linked products');
 PERFORM distribution.auth_expect_error(format('SELECT distribution.worker_action(%L,%L,%L)','item_type',jsonb_build_object('id',unit_id,'kind','category','name','Wrong kind')::text,worker_id),'cannot change');
 result:=distribution.worker_action('route','{"name":"Worker route","area":""}',worker_id);route_id:=(result->>'id')::uuid;
 result:=distribution.worker_action('customer',jsonb_build_object('name','Worker shop','credit_limit',0,'route_id',route_id),worker_id);customer_id:=(result->>'id')::uuid;
 result:=distribution.worker_action('vehicle',jsonb_build_object('number','WORKER-VEHICLE','type','Van','salesman_id',other_worker,'route_id',route_id),worker_id);vehicle_id:=(result->>'id')::uuid;
 PERFORM distribution.worker_action('inventory',jsonb_build_object('product_id',product_id,'qty',100,'kind','RECEIPT'),worker_id);
 PERFORM distribution.worker_action('load',jsonb_build_object('vehicle_id',vehicle_id,'items',jsonb_build_array(jsonb_build_object('product_id',product_id,'qty',40))),worker_id);
 PERFORM distribution.check_true((SELECT warehouse_qty=60 FROM distribution.products WHERE id=product_id),'Workers can load a vehicle assigned to another worker');
 PERFORM distribution.worker_action('vehicle_status',jsonb_build_object('vehicle_id',vehicle_id,'status','ON ROUTE'),worker_id);
 PERFORM distribution.worker_action('sale',jsonb_build_object('vehicle_id',vehicle_id,'customer_id',customer_id,'items',jsonb_build_array(jsonb_build_object('product_id',product_id,'qty',5)),'discount',0,'method','CASH','paid',50),worker_id);
 PERFORM distribution.worker_action('inventory',jsonb_build_object('product_id',product_id,'qty',3,'kind','DAMAGE','notes','Isolated damaged packaging'),worker_id);
 PERFORM distribution.worker_action('reconcile',jsonb_build_object('vehicle_id',vehicle_id,'decision','UNLOAD','items',jsonb_build_array(jsonb_build_object('product_id',product_id,'physical',35))),worker_id);
 PERFORM distribution.check_true((SELECT warehouse_qty=92 FROM distribution.products WHERE id=product_id),'Worker stock, sale and unload update the shared warehouse balance');
 PERFORM distribution.check_true((SELECT count(*)=5 AND bool_and(created_by=worker_id) FROM distribution.movements WHERE movements.product_id=product_id),'Every worker stock movement records the actual actor');
 snapshot:=distribution.daily_summary(today);
 SELECT x INTO stockrow FROM jsonb_array_elements(snapshot->'stock') x WHERE (x->>'id')::uuid=product_id;
 PERFORM distribution.check_true(stockrow @> '{"opening_warehouse":0,"opening_vehicle":0,"received":100,"loaded":40,"sold":5,"unloaded":35,"damaged":3,"closing_warehouse":92,"closing_vehicle":0}'::jsonb,'Daily report reconciles receipt, load, sale, damage and unload');
 SELECT x INTO person FROM jsonb_array_elements(snapshot->'workers') x WHERE (x->>'id')::uuid=worker_id;
 PERFORM distribution.check_true(person @> '{"orders":1,"sales":50,"collections":50,"received":100,"loaded":40,"sold":5}'::jsonb,'Daily report attributes operations to the worker who recorded them');
 request_id:=gen_random_uuid();payload:=jsonb_build_object('day',today,'notes','Isolated report notes');
 result:=distribution.worker_action('submit_daily_report',payload,worker_id,request_id);report_id:=(result->>'id')::uuid;
 PERFORM distribution.worker_action('submit_daily_report',payload,worker_id,request_id);
 PERFORM distribution.check_true((SELECT revision=1 AND summary->>'day'=today::text FROM distribution.daily_reports WHERE id=report_id),'Daily report retry creates one stored snapshot');
 PERFORM distribution.auth_expect_error(format('SELECT distribution.worker_action(%L,%L,%L)','review_daily_report',jsonb_build_object('id',report_id,'revision',1)::text,worker_id),'Permission denied');
 PERFORM distribution.apply_action('review_daily_report',jsonb_build_object('id',report_id,'revision',1),owner_id,'owner',owner_id::text,gen_random_uuid());
 PERFORM distribution.check_true((SELECT reviewed_by=owner_id AND reviewed_at IS NOT NULL FROM distribution.daily_reports WHERE id=report_id),'Admin receives and reviews the submitted worker report');
 PERFORM distribution.worker_action('submit_daily_report',payload,worker_id);
 PERFORM distribution.check_true((SELECT revision=2 AND reviewed_at IS NULL FROM distribution.daily_reports WHERE id=report_id),'A worker resubmission increments the version and needs a new review');
 PERFORM distribution.auth_expect_error(format('SELECT distribution.apply_action(%L,%L,%L,%L,%L,%L)','review_daily_report',jsonb_build_object('id',report_id,'revision',1)::text,owner_id,'owner',owner_id::text,gen_random_uuid()),'report changed');
 PERFORM distribution.auth_expect_error(format('SELECT distribution.worker_action(%L,%L,%L)','submit_daily_report',jsonb_build_object('day',today+1)::text,worker_id),'previous day');
 PERFORM distribution.worker_action('inventory',jsonb_build_object('product_id',product_id,'qty',5,'kind','RECEIPT','notes','Future movement for historical test'),worker_id);
 UPDATE distribution.movements SET created_at=now()+interval '1 day' WHERE movements.product_id=product_id AND notes='Future movement for historical test';
 snapshot:=distribution.daily_summary(today);
 SELECT x INTO stockrow FROM jsonb_array_elements(snapshot->'stock') x WHERE (x->>'id')::uuid=product_id;
 PERFORM distribution.check_true((stockrow->>'closing_warehouse')::integer=92,'Daily closing stock excludes movements recorded after the selected day');
 UPDATE distribution.products SET created_at=now()-interval '2 days' WHERE id=product_id;
 UPDATE distribution.movements SET created_at=now()-interval '1 day' WHERE movements.product_id=product_id AND notes<>'Future movement for historical test';
 snapshot:=distribution.daily_summary(today-1);
 SELECT x INTO stockrow FROM jsonb_array_elements(snapshot->'stock') x WHERE (x->>'id')::uuid=product_id;
 PERFORM distribution.check_true((stockrow->>'closing_warehouse')::integer=92 AND (stockrow->>'opening_warehouse')::integer=0,'Historical report reconstructs opening and closing stock from the ledger');
 PERFORM distribution.check_true((SELECT (x->>'closing_warehouse')::integer=92 FROM distribution.daily_reports r,jsonb_array_elements(r.summary->'stock') x WHERE r.id=report_id AND (x->>'id')::uuid=product_id),'Submitted snapshots stay unchanged when later stock changes');
END $$;
